# Generated by Django 4.2.19 on 2025-02-13 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='updated_at',
        ),
    ]
