# Generated by Django 4.2.19 on 2025-02-20 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='category',
            name='categories__parent__6ada01_idx',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent_category',
        ),
    ]
