# Generated by Django 5.1.6 on 2025-02-11 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_shipping_cost_order_tax'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping_cost',
            new_name='shipping',
        ),
    ]
