# Generated by Django 4.2.19 on 2025-02-14 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('order_confirmation', 'Order Confirmation'), ('payment_success', 'Payment Success'), ('payment_failure', 'Payment Failure'), ('password_reset', 'Password Reset'), ('wishlist_update', 'Wishlist Update'), ('review_received', 'Review Received')], max_length=50)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
            },
        ),
    ]
