# Generated by Django 5.1.6 on 2025-02-13 00:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_name_alter_product_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent_category'], name='products_ca_parent__6caaf7_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='products_pr_categor_9edb3d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['subcategory'], name='products_pr_subcate_f595a1_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand'], name='products_pr_brand_4bfaa4_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product'], name='products_pr_product_3d7874_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product'], name='products_re_product_b03620_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user'], name='products_re_user_id_1b4aeb_idx'),
        ),
    ]
