# Generated by Django 4.2.19 on 2025-02-13 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('products', '0009_alter_product_category_alter_product_subcategory_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_categor_9edb3d_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_in_category', to='categories.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_in_subcategory', to='categories.category'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['parent_category'], name='products_pr_parent__ecf896_idx'),
        ),
    ]
