# Generated by Django 4.2.19 on 2025-02-14 13:04

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('products', '0013_alter_product_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(
                blank=True, help_text='Brand of the product.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category of the product.', null=True,
                                    on_delete=django.db.models.deletion.SET_NULL, related_name='products_in_category', to='categories.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, help_text='Timestamp when the product was created.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(
                help_text='Detailed description of the product.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discounted_price',
            field=models.DecimalField(
                blank=True, decimal_places=2, help_text='Discounted price of the product (if applicable).', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='features',
            field=models.JSONField(
                default=list, help_text='List of features of the product.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(
                help_text='The name of the product.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(
                decimal_places=2, help_text='Price of the product.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(
                blank=True, help_text='Average rating of the product.', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.JSONField(
                default=dict, help_text='Specifications of the product.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(
                default=0, help_text='Available stock of the product.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, help_text='Subcategory of the product (must belong to the selected category).', null=True,
                                    on_delete=django.db.models.deletion.SET_NULL, related_name='products_in_subcategory', to='categories.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.JSONField(
                default=list, help_text='Tags associated with the product.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(
                auto_now=True, help_text='Timestamp when the product was last updated.'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=cloudinary.models.CloudinaryField(
                help_text='Image of the product.', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='is_main',
            field=models.BooleanField(
                default=False, help_text='Whether this is the main image of the product.'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(help_text='The product this image belongs to.',
                                    on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='products.product'),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=(
                'product', 'is_main'), name='unique_main_image_per_product'),
        ),
    ]
