# Generated by Django 4.2.19 on 2025-02-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_product_color_product_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_rating_sum',
            field=models.FloatField(default=0.0, help_text='Sum of all ratings for the product.'),
        ),
        migrations.AddField(
            model_name='product',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0, help_text='Total number of reviews for the product.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=0.0, help_text='Average rating of the product.'),
        ),
    ]
